### ISSUE TITLE
debuild err

### ISSUE THREAD

**Issue by darcyfdu** [armijnhemel/binaryanalysis#5] opened 2017-04-26 10:17 UTC
this is info when i tried to debuild the deb:
darcy@darcy-pc:~/binaryanalysis/src$ sudo debuild -uc -us 
dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: info: source package bat
dpkg-buildpackage: info: source version 36.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Armijn Hemel <armijn@binaryanalysis.org>
 dpkg-source --before-build src
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean --with python2
dh: Compatibility levels before 9 are deprecated (level 7 in use)
   dh_testdir
   dh_auto_clean
dh_auto_clean: Compatibility levels before 9 are deprecated (level 7 in use)
dh_auto_clean: pyversions -d failed [1]
debian/rules:13: recipe for target 'clean' failed
make: *** [clean] Error 1
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

**Comment by armijnhemel** [comment] 2017-07-02 10:40
I just rebuilt on Debian 9 and I cannot reproduce this problem. I will update the compatibility levels though.

**Comment by armijnhemel** [comment] 2017-09-30 18:02
BAT is no longer maintained, closing.

**Closed as completed by armijnhemel** 2017-09-30 18:02 UTC
